language: ruby
rvm:
  - 2.3.1
  - 2.2.4
  - 2.1.8
  - 2.0.0
env:
  - RSPEC_VERSION=3.0.0
  - RSPEC_VERSION=3.1.0
  - RSPEC_VERSION=3.2.0
  - RSPEC_VERSION=3.3.0
  - RSPEC_VERSION=3.4.0
  - RSPEC_VERSION=3.5.0.beta4
before_install: gem install bundler -v 1.11.2
